/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(manchester.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(7e80b122a9f69f9e09ab26ef6219a0f4)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/bbq/manchester.h>
// pydoc.h is automatically generated in the build directory
#include <manchester_pydoc.h>

void bind_manchester(py::module& m)
{

    using manchester    = gr::bbq::manchester;


    py::class_<manchester, gr::block, gr::basic_block,
        std::shared_ptr<manchester>>(m, "manchester", D(manchester))

        .def(py::init(&manchester::make),
           D(manchester,make)
        )
        



        ;




}








