/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(packet_parser.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(34a377401b7fa0058a3aaf149266dc99)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/bbq/packet_parser.h>
// pydoc.h is automatically generated in the build directory
#include <packet_parser_pydoc.h>

void bind_packet_parser(py::module& m)
{

    using packet_parser    = gr::bbq::packet_parser;


    py::class_<packet_parser, gr::block, gr::basic_block,
        std::shared_ptr<packet_parser>>(m, "packet_parser", D(packet_parser))

        .def(py::init(&packet_parser::make),
           D(packet_parser,make)
        )
        



        ;




}








